config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :coupons, controller: 'coupon', only: %i[new create destroy] do
    collection do
      post 'issue', to: 'coupon#issue'
      get 'wallet', to: 'coupon#wallet'
      get 'list', to: 'coupon#index'
    end
  end

  # Health check
  get 'up', to: 'rails/health#show', as: :rails_health_check

  # Root path
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/concerns/retryable.rb
module Retryable
  def retry_on_lock_error(max_retries = 3)
    retries = 0
    begin
      yield
    rescue ActiveRecord::StatementInvalid => e
      if retries < max_retries
        retries += 1
        Rails.logger.warn("Database lock encountered, retrying... (#{retries}/#{max_retries})")
        sleep(1)
        retry
      else
        raise e
      end
    end
  end
end

app/models/coupon_detail.rb
# id: integer (PK)

# amount: integer

# name: string

# max_amount_per_user: integer

# discount_value: integer

# created_at: datetime - not null

# updated_at: datetime - not null

# deleted_at: datetime

# duration_day: intege
class CouponDetail < ApplicationRecord
  acts_as_paranoid

  has_many :coupon_wallets, dependent: :destroy

  validates :name, presence: true
  validates :amount, presence: true, numericality: { greater_than_or_equal_to: 1 }
  validates :max_amount_per_user, presence: true, numericality: { greater_than_or_equal_to: 1 }
  validates :discount_value, presence: true, numericality: { greater_than_or_equal_to: 1 }

  def sold_out?
    Rails.logger.error("coupon amount is negative; coupon: #{id}") if amount < 0

    amount <= 0
  end
end

app/models/coupon_purchase.rb
class CouponPurchase < ApplicationRecord
  acts_as_paranoid

  belongs_to :coupon_detail, foreign_key: :coupon_id
  

end

app/models/coupon_wallet.rb
class CouponWallet < ApplicationRecord
  acts_as_paranoid

  belongs_to :user
  belongs_to :coupon_detail, foreign_key: :coupon_id
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
  attribute :request_id, :user_agent, :ip_address
  
  def user=(user)
    super
  end

end

app/models/user.rb
# t.string "email", default: "", null: false
# t.string "encrypted_password", default: "", null: false
# t.string "reset_password_token"
# t.datetime "reset_password_sent_at"
# t.datetime "remember_created_at"
# t.datetime "created_at", null: false
# t.datetime "updated_at", null: false
# t.string "nickname"
# t.index ["email"], name: "index_users_on_email", unique: true
# t.index ["reset_password_token"], name: "index_users_on_reset_password_token", unique: true

class User < ApplicationRecord
  enum role: { user: 0, admin: 1, guest: 2 }

  has_many :coupon_wallets, dependent: :destroy

  before_create :set_default_role

  after_initialize :set_default_role, if: :new_record?

  acts_as_paranoid

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def set_default_role
    return self.role = :admin if id == 1

    self.role ||= :user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!
  helper_method :current_user, :user_signed_in?
  rescue_from ExceededMaxAmountPerUser, with: :exceeded_max_amount_per_user
  rescue_from CouponSoldOut, with: :coupon_sold_out

  private

  def exceeded_max_amount_per_user(error)
    Rails.logger.error("Coupon issue has reached to limit: #{error.message}")
    render json: { message: 'Coupon issue has reached to limit' }, status: :bad_request
  end

  def coupon_sold_out
    Rails.logger.error("Coupon sold out: #{error.message}")
    render json: { message: 'Coupon sold out' }, status: :bad_request
  end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/concerns/authentication.rb
module Authentication
  extend ActiveSupport::Concern

  included do
    before_action :set_current_user
  end

  def set_current_user
    if authenticated_user = User.find_by(id: cookies.encrypted[:user_id])
      Current.user = authenticated_user
    else
      redirect_to new_session_url
    end
  end

end

app/controllers/concerns/set_current_request_details.rb
module SetCurrentRequestDetails
  extend ActiveSupport::Concern

  included do
    before_action do
      Current.request_id = request.uuid
      Current.user_agent = request.user_agent
      Current.ip_address = request.ip
    end
  end
end

app/controllers/coupon_controller.rb
class CouponController < ApplicationController
  before_action :check_user, only: %i[issue wallet]
  before_action :check_admin, only: %i[create new]

  def check_user
    return if current_user.user? || current_user.admin?

    head :unauthorized
  end

  def check_admin
    return if current_user.admin?

    head :unauthorized
  end

  def coupon_params
    params.require(:coupon_detail).permit(:name, :amount, :max_amount_per_user, :discount_value, :duration_day)
  end

  def new
    @coupon_detail = CouponDetail.new
    render '/coupon/new_coupon'
  end

  def create
    @coupon_detail = CouponDetail.create!(coupon_params)

    redirect_to list_coupons_path
  end

  # TODO: paging
  def index
    # CouponDto
    @coupon_details = CouponReader.new.read_all
    render 'coupon/list'
  end

  # TODO: paging
  def wallet
    user = current_user
    @coupon_wallets = CouponWallet.where(user_id: user.id).includes(:coupon_detail)
    render 'coupon/wallet'
  end

  def issue
    left_coupon_amount = 0

    user_id = current_user.id

    begin
      left_coupon_amount = CouponService.new.purchase_coupon(user_id, params[:coupon_id])
    rescue StandardError => e
      Rails.logger.error("Error: #{e.message}")
      render json: { message: e.message }, status: :internal_server_error
      return
    rescue ActiveRecord::RecordInvalid => e
      Rails.logger.error("Validation error: #{e.message}")
      render json: { message: e.message }, status: :unprocessable_entity
      return
    end

    render json: { message: 'Coupon issued successfully', left_amount: left_coupon_amount }, status: :ok
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/coupon/list.erb
<% @coupon_details.each do |coupon| %>

    <div data-id = "<%= coupon.id %>">
        
        <h3><%= coupon.name %></h3>
        <p class='coupon-amount'>Amount: <%= coupon.amount %></p>
        <p>Max Amount Per User: <%= coupon.max_amount_per_user %></p>
        <p>Discount Value: <%= coupon.discount_value %></p>
        <p>Duration (in Days): <%= coupon.duration_day %></p>

        <button class="coupon-issue">issue</button>
    </div>

<% end %>


<script type="module" >

    function getCsrfToken() {
        return document.querySelector('meta[name="csrf-token"]').getAttribute('content');
    }
    
    async function postRequest(url, data) {
        const response = await fetch(url, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'X-CSRF-Token': getCsrfToken(),
            },
            body: JSON.stringify(data),
        });
        return response;
    }
    
    async function handleCouponIssue(event) {
        const button = event.target;
        const couponId = button.closest('div[data-id]').getAttribute('data-id');
        const url = "<%= url_for(controller: 'coupon', action: 'issue', only_path: true) %>";
    
        try {
            const response = await postRequest(url, { coupon_id: couponId });
    
            if (response.ok) {
                const data = await response.json();
                const leftAmount = data.left_amount;
    
                document.querySelector(`div[data-id="${couponId}"] .coupon-amount`).innerText = `Amount: ${leftAmount}`;
    
                alert('Coupon Issued');
            } 
            
            else if (response.unprocessable_entity) {
                const error = await response.json();
                console.log('response:', error.message);
                alert('You are not authorized to issue this coupon');
            }

            else {
                const error = await response.json();
                alert(error.message);
            }
        } catch (error) {
            console.error('Error issuing coupon:', error);
            alert('An unexpected error occurred');
        }
    }
    
    document.querySelectorAll('.coupon-issue').forEach((button) => {
        button.addEventListener('click', handleCouponIssue);
    });
    
</script>

app/views/coupon/new_coupon.erb
<h1>Create a New Coupon</h1>


<%= form_with model: @coupon_detail, url: coupons_path, method: :post, local: true do |f| %>
  <div>
    <%= f.label :name, "Name" %>
    <%= f.text_field :name, required: true %>
  </div>

  <div>
    <%= f.label :amount, "Amount" %>
    <%= f.text_field :amount, required: true %>
  </div>

  <div>
    <%= f.label :max_amount_per_user, "Max Amount Per User" %>
    <%= f.number_field :max_amount_per_user, required: true %>
  </div>

  <div>
    <%= f.label :discount_value, "Discount Value" %>
    <%= f.number_field :discount_value, required: true %>
  </div>

  <div>
    <%= f.label :duration_day, "Duration (in Days)" %>
    <%= f.number_field :duration_day %>
  </div>

  <div>
    <%= f.submit "Create Coupon" %>
  </div>
<% end %>

app/views/coupon/wallet.erb
<% @coupon_wallets.each do |coupon|%>

<div data-id="<%= coupon.id %>">
    <h3><%= coupon.coupon_detail.name %></h3>
    <p>Discount Value: <%= coupon.coupon_detail.discount_value%><p>
    <p class="coupon-amount">Amount: <%= coupon.amount %></p>
    <p> expire date: <%= coupon.expire_date %></p>
</div>

<br/>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TicketService</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>